### ISSUE TITLE
Adding StopLoss order to empty orderbook

### ISSUE THREAD

**Issue by Masorubka1** [geseq/orderbook#18]
```
func (ob *OrderBook) addTrigOrder(id uint64, class ClassType, side SideType, quantity, price, stPrice decimal.Decimal, flag FlagType) {
	fmt.Printf("Adding trig order: ID=%d, Class=%v, Side=%v, Qty=%s, Price=%s, TriggerPrice=%s, Flag=%v\n",
		id, class, side, quantity.String(), price.String(), stPrice.String(), flag)

	switch flag {
	case StopLoss:
		switch side {
		case Buy:
			if stPrice.LessThanOrEqual(ob.lastPrice) {
				fmt.Printf("Triggering stop buy order immediately cause price %s", ob.lastPrice.String())
				ob.processOrder(id, class, side, quantity, price, flag)
				return
			}
			ob.trigOrders.Put(id, ob.triggerOver.Append(NewOrder(id, class, side, quantity, price, stPrice, flag)))
			fmt.Println("Added stop buy order to triggerOver")
		case Sell:
			if !ob.lastPrice.IsZero() && ob.lastPrice.LessThanOrEqual(stPrice) {
				fmt.Printf("Triggering stop buy order immediately cause price %s", ob.lastPrice.String())
				ob.processOrder(id, class, side, quantity, price, flag)
				return
			}
			ob.trigOrders.Put(id, ob.triggerUnder.Append(NewOrder(id, class, side, quantity, price, stPrice, flag)))
			fmt.Println("Added stop sell order to triggerUnder")
		}
	}
}
```

in case ob.lastPrice was never initialized StopLoss would execute imidiately, but in reality StopLoss have to stay in orderbook till last price won`t update

**Comment by geseq** [comment]
That's not what happens. This part of the code just adds trigger orders to a queue. It doesn't actually execute them. Execution at absence of last price is blocked here:
https://github.com/geseq/orderbook/blob/main/orderbook.go#L245

This is also accounted for in the unit test `TestStopProcess` where we initially add a depth and a stop loss order but it does not trigger until a limit price change.

If you still see something incorrect please reopen the issue with a test case.

**Comment by geseq** [comment]
As a side note, in a production use case you might be better off queuing trigger orders outside of the matching thread for best effort execution to reduce jitter on incoming requests.
